alert:
- debug
description: This rule detects a DNS server error in which a specified plugin DLL (in registry) could not be loaded
filter:
- query:
    query_string:
      query: (winlog.channel:"DNS\ Server" AND winlog.event_id:("150" OR "770"))
index: winlogbeat-*
name: cbe51394-cd93-4473-b555-edf0144952d9-DNS-Server-Error-Failed-Loading-the-ServerLevelPluginDLL
priority: 1
realert:
  minutes: 0
type: any

import: BaseHive.config
import: BaseTeams.config
import: BaseRule.config
