alert:
- debug
description: This rule will monitor any office apps that spins up a new LOLBin process. This activity is pretty suspicious and should be investigated.
filter:
- query:
    query_string:
      query: (Image.keyword:(*regsvr32 OR *rundll32 OR *msiexec OR *mshta OR *verclsid) AND ParentImage.keyword:(*winword.exe OR *excel.exe OR *powerpnt.exe))
index: filebeat-*
name: 23daeb52-e6eb-493c-8607-c4f0246cb7d8-New-Lolbin-Process-by-Office-Applications
priority: 2
realert:
  minutes: 0
type: any

import: BaseHive.config
import: BaseTeams.config
import: BaseRule.config
