alert:
- debug
description: Detects Obfuscated use of Environment Variables to execute PowerShell
filter:
- query:
    query_string:
      query: (EventID:"4697" AND ServiceFileName.keyword:/.*cmd.{0,5}(?:\/c|\/r)(?:\s|)\"set\s[a-zA-Z]{3,6}.*(?:\{\d\}){1,}\\\"\s+?\-f(?:.*\)){1,}.*\"/)
index: filebeat-*
name: dcf2db1f-f091-425b-a821-c05875b8925a-Invoke-Obfuscation-VAR+-Launcher
priority: 2
realert:
  minutes: 0
type: any

import: BaseHive.config
import: BaseTeams.config
import: BaseRule.config
